<html>
    <head>
        <title>@yield('title')</title>
        @yield('head')
    </head>
    <body>
        @yield('2034-content')        
        @yield('2038-content')
        @yield('2033-content')
        @yield('2043-content')
        @yield('2042-content')
        @yield('2039-content')
        @yield('2035-content')
        @yield('2040-content')
        @yield('2036-content')
        @yield('2041-content')
        @yield('2037-content')
        @yield('2044-content')
    </body>
</html>
